### PR TITLE
server: Replace string/parse trick for cloning with more efficient option.

### PR DESCRIPTION
**Pull request by calebcase**

### CODE REVIEW

**Comment by aspacca** [comment]
thanks @calebcase , while you are at it do you mind checking for `nil` return?

**Comment by calebcase** [comment]
> thanks @calebcase , while you are at it do you mind checking for `nil` return?

NP, nil check added

**Comment by aspacca** [comment]
@calebcase now also `getURL` can return `nil` and it should be checked anywhere.
I wonder if the `nil` check is needed at all, can ever `http.Request.URL` be `nil`?

**Comment by calebcase** [comment]
@aspacca I think this was a problem before. `r.URL` has paths where it could be `nil`. If it is, then the old code would have segfaulted at `r.URL.String()` (https://play.golang.org/p/LZ45LIv6bB6).

It may be better to establish an invariant earlier in the request processing to avoid having to have nil checks throughout the code base.

**Comment by aspacca** [comment]
according to https://github.com/golang/go/blob/master/src/net/http/request.go#L1052 the request will never reach the handler if the url cannot be parsed, so we can assume `r.URL` will not be nil

**Comment by aspacca** [comment]
@calebcase still working on this?

**Comment by aspacca** [comment]
@calebcase if there's no update I'm going to close the PR and implement personally

**Comment by calebcase** [comment]
Yup, please do!

**Pull request closed without merging**
