### PR TITLE
ISSUE-44 delete support

### LINKED ISSUE #44: DELETE a file ?
`curl -X DELETE https://transfer.sh/xf54d/myfile.password`
would be awesome.

### PR DESCRIPTION
**Pull request by aspacca**
Fixes #44

### CODE REVIEW

**Comment by aspacca** [comment]
@nl5887 I cannot test on S3

**Comment by rogerkerse** [comment]
As I understand, transfer.sh has delete support, but how it works? Any examples?

**Comment by aspacca** [comment]
@rogerkerse , @cegohub the upstream version of the source code returns the header `X-Url-Delete` with an url where to send a `DELETE` request to for deleting the file. The header is returned only once on uploading the file. With access to the backend storage is possible to read the metadata to build back the delete url.
Said this, transfer.sh, as hosting service, is not updated to upstream source code, so there's no way to delete a file.

**Comment by cegohub** [comment]
> @rogerkerse , @cegohub the upstream version of the source code returns the header `X-Url-Delete` with an url where to send a `DELETE` request to for deleting the file. The header is returned only once on uploading the file. With access to the backend storage is possible to read the metadata to build back the delete url.
> Said this, transfer.sh, as hosting service, is not updated to upstream source code, so there's no way to delete a file.

Hi, @aspacca  
There is a way to unlist the url path generated from my transfer?

**Comment by aspacca** [comment]
@cegohub what do you mean by unlist? 
anyway I have no control on the hosting service at transfer.sh, you may want to contact directly https://storj.io/

**Pull request merged**
